CREATE TABLE IF NOT EXISTS users
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    username         VARCHAR(50),
    password         VARCHAR(50),
    password_confirm VARCHAR(50)
);

CREATE TABLE IF NOT EXISTS tasks
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    name           VARCHAR(50)                             NOT NULL,
    status         VARCHAR(20)                             NOT NULL,
    type           VARCHAR(20)                             NOT NULL,
    created        TIMESTAMP                               NOT NULL,
    status_changed TIMESTAMP,
    information    VARCHAR(200),
    project_id     BIGINT,
    subproject_id  BIGINT,
    user_id        BIGINT NOT NULL,
    CONSTRAINT FK_TASK_ON_PROJECT FOREIGN KEY (project_id) REFERENCES projects (id),
    CONSTRAINT FK_TASK_ON_SUBPROJECT FOREIGN KEY (subproject_id) REFERENCES subprojects (id),
    CONSTRAINT FK_TASK_ON_USER FOREIGN KEY (user_id) REFERENCES users (id)
);

CREATE TABLE IF NOT EXISTS projects
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    name VARCHAR(50) NOT NULL,
    user_id BIGINT,
    CONSTRAINT FK_PROJECT_ON_USER FOREIGN KEY (user_id) REFERENCES users (id)
);

CREATE TABLE IF NOT EXISTS subprojects
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    name VARCHAR(50) NOT NULL,
    user_id BIGINT,
    description VARCHAR(200),
    project_id BIGINT NOT NULL,
    CONSTRAINT FK_SUBPROJECT_ON_USER FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT FK_SUBPROJECT_ON_PROJECT FOREIGN KEY (project_id) REFERENCES projects (id)
);

CREATE TABLE IF NOT EXISTS role
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    name VARCHAR(20)
);